### PR TITLE
fix static dependencies error

### PR DESCRIPTION
**Pull request by DeadBryam**
solving issue https://github.com/nateshmbhat/card-scanner-flutter/issues/7

### CODE REVIEW

**Comment by m-zaink** [comment]
@DeadBryam 
Did this work for lower iOS versions? Such as 11.0 and 10.0?

And can you give me more context as to what this PR is trying to do?

**Comment by DeadBryam** [comment]
I'm sorry for the delay.
When I tried to compile the app in IOS it gave me the same error as https://github.com/nateshmbhat/card-scanner-flutter/issues/7. After investigating I found that adding s.static_framework = true the podspec of the library could solve the error.

for more information
https://blog.cocoapods.org/CocoaPods-1.4.0/
in the section "Static Frameworks"

**Comment by m-zaink** [comment]
That's awesome @DeadBryam.
I'll close this issue then.

Glad it worked. ✌️

**Comment by jamesdixon** [comment]
@nateshmbhat this fixes the need to comment out `!use_frameworks`. Any chance of getting this merged?

**Comment by m-zaink** [comment]
@jamesdixon thanks bud. This works. Merging.

**Review by m-zaink — APPROVED** [review]
LGTM

**Pull request merged**
